### PR TITLE
Feature: Webpack

### PR DESCRIPTION
**Pull request by tmeloliveira**
##### Done in this PR

In this PR I'm adding the necessary config to use webpack with middleman.

This config was inspired by this [blog post](https://rossta.net/blog/using-webpack-with-middleman.html) and [this repo](https://github.com/MaxHill/middleman-start). Which I definitely recommend taking a look.

The things I did in this PR were:
* Adding `webpack.config.js` file.
* Added config for [external pipeline](https://middlemanapp.com/advanced/external-pipeline/) on `config.rb` file.
* Removed sprockets and coffee-script imports from Gemfile.
* Transfered our coffee code to a new JS file.

In order to run this code, you should just do a `yarn install` and `bundle install` before running `middleman s`. Other than that, everything should work as before.

##### To-do
- [x] Add config for DEV and PROD environments.
- [x] Improve our JS file organization/structure.
- [x] Make sure everything still works. 🙃 

Please review it, @startae/frontend-team.

### CODE REVIEW

**Comment by tmeloliveira** [comment]
After fixing an issue, the deploy to netlify seems to be working just fine! 🙂

**Comment by renatocarvalho** [comment]
The deploy on Netlify started to fail 😬

**Comment by tmeloliveira** [comment]
Yep, I'm aware. Working on some changes locally here...

**Comment by tmeloliveira** [comment]
Fixed the issues running locally. But the production build is not working... 😓 
Investigating this!

**Comment by tmeloliveira** [comment]
OK, now I think it's ready for review! 🙏

**Comment by sales** [comment]
Beautiful! I just tested locally and it worked like a charm. 👌

**Comment by renatocarvalho** [comment]
The CSS part seems to not be working. Are we going to include the adjustments on this PR or should we create another task and PR for it?

**Comment by renatocarvalho** [comment]
Everything else is looking great!

**Comment by tmeloliveira** [comment]
The CSS is working for me @renatocarvalho 

The thing is, on the [inuit cleanup PR](https://github.com/startae/middleman-startae/pull/30/files), we've removed most of the styles we had for the home page. So that's why it looks like there are no styles applied to the markup... because there aren't any.

I think we can close this one, and make the style modifications discussed on flow in another PR.

**Comment by tmeloliveira** [comment]
As this branch is only targeting `feature/new-version`, I'm gonna go ahead and merge it.

In case something happens... it's my fault anyways... 😅

**Pull request merged**
