### PR TITLE
Update template usage instructions

### PR DESCRIPTION
**Pull request by sales**
##### Done in this PR
- Update and simplify template usage instructions

_Resource: https://middlemanapp.com/advanced/project-templates#github-template_

Please review it, @startae/frontend-team.

### CODE REVIEW

**Comment by renatocarvalho** [comment]
Looks good, but I have one suggestion. I think we could simplify even more our instructions. Can I commit here?

**Comment by sales** [comment]
Yeap, @renatocarvalho! :)

**Comment by renatocarvalho** [comment]
Let's ship like this and then improve later. I got sick and that messed with my time. Merging over here, ok?

**Comment by sales** [comment]
👍

**Pull request merged**
