### PR TITLE
New version

### PR DESCRIPTION
**Pull request by renatocarvalho**
Please review it, @startae/frontend-team.

### CODE REVIEW

**Comment by tmeloliveira** [comment]
A little hard to review with `+4,194 −12,278`  and 190 files changed. 😅 
So, just ship it! :shipit:

**Comment by sales** [comment]
LGTM! :rocket: :shipit:

**Comment by renatocarvalho** [comment]
hahaha

**Comment by renatocarvalho** [comment]
If anything happens, it's @tmeloliveira's fault 😂

**Pull request merged**
