### PR TITLE
Use itcsscli and remove inuit

### PR DESCRIPTION
**Pull request by kandebonfim**
Please review it, @startae/frontend-team.

### CODE REVIEW

**Review by renatocarvalho — CHANGES_REQUESTED** [review]
PR looks great @kandebonfim 👌. Can you just update the README adding the info about itcsscli?

**Review by tmeloliveira — CHANGES_REQUESTED** [review]
@kandebonfim when we started this changes on middleman-startae, we decided to merge everything into a branch separate from `develop`. This branch is `feature/new-version`.

Can you please retarget your PR to this branch?

If you want to take a look, that is a PR that has already been merged: https://github.com/startae/middleman-startae/pull/28

**Comment by renatocarvalho** [comment]
@tmeloliveira I think this change can be added to `develop` since it's removing inuit. It's something that we would need to do right now.

**Comment by tmeloliveira** [comment]
@renatocarvalho but the other PR I mentioned (#28) already removed a bunch of **inuit**. 
I just wanted them to be "merged" together. That is a lot of rework here, that was done in the other PR already.

The best way to do this IMHO, is to retarget this PR to the branch `feature/new-version`. And then we could send it to develop.

Then, the other PR regarding `webpack` could come later on.

**Comment by renatocarvalho** [comment]
Got it @tmeloliveira. It makes sense. Can you retarget to `feature/new-version` @kandebonfim?

**Comment by kandebonfim** [comment]
@tmeloliveira :shipit: ?

**Pull request merged**
