### PR TITLE
Feature/updates

### PR DESCRIPTION
**Pull request by renatocarvalho**
- Update polyfills scripts
- Update Gems
- Update Bower components
- Organize sass files
- Add motion tools
- Add ellipsis tool
- Remove Susy configuration
- Several adjustments and cleanup

### CODE REVIEW

**Comment by renatocarvalho** [comment]
@startae/frontend-team

**Comment by romulomachado** [comment]
LGTM! :shipit:

**Comment by sales** [comment]
It worked fine! 👌 

:shipit:

**Comment by renatocarvalho** [comment]
Thanks :)

**Pull request merged**
